
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.util.ArrayList;
import java.sql.Date;
import java.text.SimpleDateFormat;
import java.util.List;

import javax.swing.JLabel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nelson
 */
public class GUIFrame extends javax.swing.JFrame {
    
    private static Connection connection;
    private static PreparedStatement InsertCustomers;
    private static PreparedStatement InsertDays;
    private static PreparedStatement InsertBooking;
    
    private static final String URL = "jdbc:derby://localhost:1527/FlightSchedulerDBNelsonnmh5395";
    private static final String USERNAME = "java";
    private static final String PASSWORD = "java";
    
    private final JLabel jLabel3;
    private static double FlightName;
    private static int seats;
        
    private static PreparedStatement selectAllPeople;
    private static PreparedStatement selectAllFlights;
    /**
     * Creates new form GUIFrame
     */
    public GUIFrame() {
        initComponents();
        Flight_booking_combo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        Customers_booking_combo.setModel(new javax.swing.DefaultComboBoxModel(Customer.getCustomer().toArray()));
        Dates_booking_combo.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        Flight_booking_combo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        Dates_booking_combo.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        
        Delete_customer_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Customer.getCustomer().toArray()));
        Delete_day_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        Delete_flight_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        
        Flight_status_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        Date_status_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        Customer_status_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Customer.getCustomer().toArray()));
        
        Date_waitlist_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
                
        jLabel3 = new JLabel("Name already exists.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CustomerNameTextField = new javax.swing.JTextField();
        AddCustomerButton = new javax.swing.JButton();
        customer_added_jLabel = new javax.swing.JLabel();
        FlightNameTextField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        NumberOfSeatsTextField = new javax.swing.JTextField();
        AddFlightName = new javax.swing.JButton();
        DateSpinner = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        AddDate = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Flight_booking_combo = new javax.swing.JComboBox<>();
        AddBooking = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Customers_booking_combo = new javax.swing.JComboBox<>();
        Dates_booking_combo = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Booking_label = new javax.swing.JLabel();
        Booking_label_2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        Delete_customer_combo_box = new javax.swing.JComboBox<>();
        Delete_day_combo_box = new javax.swing.JComboBox<>();
        Delete_flight_combo_box = new javax.swing.JComboBox<>();
        cancel_booking_button = new javax.swing.JButton();
        Drop_button = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightStatusTextArea = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        FlightANDdate_status_button = new javax.swing.JButton();
        Flight_status_combo_box = new javax.swing.JComboBox<>();
        Date_status_combo_box = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Customer_status_combo_box = new javax.swing.JComboBox<>();
        customer_status_button = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Waitlist_text_area = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        Date_waitlist_combo_box = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        Date_waitlist_button = new javax.swing.JButton();

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Flight Scheduler");

        jLabel2.setText("Customer Name: ");

        CustomerNameTextField.setColumns(20);
        CustomerNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CustomerNameTextFieldActionPerformed(evt);
            }
        });

        AddCustomerButton.setText("Add");
        AddCustomerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddCustomerButtonActionPerformed(evt);
            }
        });

        FlightNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightNameTextFieldActionPerformed(evt);
            }
        });

        jLabel12.setText("# of Seats:");

        NumberOfSeatsTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NumberOfSeatsTextFieldActionPerformed(evt);
            }
        });

        AddFlightName.setText("Add");
        AddFlightName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFlightNameActionPerformed(evt);
            }
        });

        DateSpinner.setModel(new javax.swing.SpinnerDateModel());

        jLabel16.setText("Flight Name: ");

        AddDate.setText("Add");
        AddDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(AddDate))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel16)
                            .addComponent(jLabel2))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(CustomerNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddCustomerButton))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FlightNameTextField)
                                    .addComponent(NumberOfSeatsTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddFlightName)))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(customer_added_jLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel15)
                            .addComponent(jLabel19))))
                .addGap(16, 16, 16))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(customer_added_jLabel))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(CustomerNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddCustomerButton)
                            .addComponent(jLabel15))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(FlightNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(NumberOfSeatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(AddFlightName)
                                    .addComponent(jLabel17))))))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DateSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddDate)
                    .addComponent(jLabel19))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Create", jPanel1);

        Flight_booking_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Flight_booking_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Flight_booking_comboActionPerformed(evt);
            }
        });

        AddBooking.setText("Add Booking");
        AddBooking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBookingActionPerformed(evt);
            }
        });

        jLabel4.setText("Choose Flights: ");

        Customers_booking_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Customers_booking_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customers_booking_comboActionPerformed(evt);
            }
        });

        Dates_booking_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setText("Choose Customers: ");

        jLabel6.setText("Choose Dates: ");

        Booking_label.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(AddBooking))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(Dates_booking_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Flight_booking_combo, 0, 256, Short.MAX_VALUE)
                                    .addComponent(Customers_booking_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                .addContainerGap(152, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(204, 204, 204)
                .addComponent(Booking_label)
                .addGap(44, 44, 44)
                .addComponent(Booking_label_2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Customers_booking_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Flight_booking_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Dates_booking_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(AddBooking)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Booking_label_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Booking_label)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Add Booking", jPanel2);

        Delete_customer_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Delete_day_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        Delete_flight_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cancel_booking_button.setText("Cancel");
        cancel_booking_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_booking_buttonActionPerformed(evt);
            }
        });

        Drop_button.setText("Drop");
        Drop_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Drop_buttonActionPerformed(evt);
            }
        });

        jLabel18.setText("Flight");

        jLabel20.setText("Customer");

        jLabel21.setText("Day");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel20)
                    .addComponent(jLabel18))
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(Delete_day_combo_box, javax.swing.GroupLayout.Alignment.LEADING, 0, 227, Short.MAX_VALUE)
                    .addComponent(Delete_customer_combo_box, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Delete_flight_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cancel_booking_button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addComponent(jLabel23)
                        .addGap(66, 66, 66))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(Drop_button, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel22)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cancel_booking_button)
                            .addComponent(jLabel23)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Delete_customer_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Delete_day_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21))))
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Delete_flight_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Drop_button)
                    .addComponent(jLabel18)
                    .addComponent(jLabel22))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cancel/Drop", jPanel5);

        FlightStatusTextArea.setColumns(20);
        FlightStatusTextArea.setRows(5);
        jScrollPane1.setViewportView(FlightStatusTextArea);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("View Current Flight Status");

        FlightANDdate_status_button.setText("OK");
        FlightANDdate_status_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FlightANDdate_status_buttonActionPerformed(evt);
            }
        });

        Flight_status_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Flight_status_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Flight_status_combo_boxActionPerformed(evt);
            }
        });

        Date_status_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Date_status_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_status_combo_boxActionPerformed(evt);
            }
        });

        jLabel14.setText("Date");

        jLabel13.setText("Flight");

        jLabel7.setText("Customer");

        Customer_status_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        Customer_status_combo_box.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Customer_status_combo_boxActionPerformed(evt);
            }
        });

        customer_status_button.setText("OK");
        customer_status_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customer_status_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(57, 57, 57))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(FlightANDdate_status_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(108, 108, 108))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(Flight_status_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(47, 47, 47)
                        .addComponent(Date_status_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Customer_status_combo_box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(customer_status_button, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(108, 108, 108)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Flight_status_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Date_status_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FlightANDdate_status_button)
                        .addGap(32, 32, 32)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Customer_status_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(customer_status_button))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );

        jTabbedPane1.addTab("Status", jPanel3);

        Waitlist_text_area.setColumns(20);
        Waitlist_text_area.setRows(5);
        jScrollPane2.setViewportView(Waitlist_text_area);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("View Current Waitlist");

        Date_waitlist_combo_box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel11.setText("Choose a date: ");

        Date_waitlist_button.setText("Enter");
        Date_waitlist_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Date_waitlist_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(203, 203, 203)
                .addComponent(jLabel10)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Date_waitlist_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(Date_waitlist_button)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Date_waitlist_combo_box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Date_waitlist_button))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69))
        );

        jTabbedPane1.addTab("Waitlist", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBookingActionPerformed
        // TODO add your handling code here:
        Object options = Flight_booking_combo.getSelectedItem();
        Object options1 = Customers_booking_combo.getSelectedItem();
        Object options2 = Dates_booking_combo.getSelectedItem();
        
        int count = 0;
        int seats = 0;
        
        count = BookingEntry.getFlightSeats(options.toString(), Date.valueOf(options2.toString()));
        seats = Flight.getSeats(Flight_booking_combo.getSelectedItem().toString());
        
        if (count < seats) {
            new BookingEntry().addBooking(options, options1, options2);
            Booking_label.setText("Booking Added");
        }
        
        else {
            new Waitlist().addWaitList(options, options1, options2);
            remove(Booking_label);
            Booking_label_2.setText("Booking added to Waitlist");
        }
    }//GEN-LAST:event_AddBookingActionPerformed

    private void AddCustomerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddCustomerButtonActionPerformed
        // TODO add your handling code here:
        String textfield = CustomerNameTextField.getText();
        new Customer().addCustomer(textfield);

        Customers_booking_combo.setModel(new javax.swing.DefaultComboBoxModel(Customer.getCustomer().toArray()));
        Delete_customer_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Customer.getCustomer().toArray()));
        Customer_status_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Customer.getCustomer().toArray()));
        
        jLabel15.setText("Customer Added");
    }//GEN-LAST:event_AddCustomerButtonActionPerformed

    private void CustomerNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CustomerNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CustomerNameTextFieldActionPerformed

    private void Customers_booking_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customers_booking_comboActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_Customers_booking_comboActionPerformed

    private void Flight_status_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Flight_status_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Flight_status_combo_boxActionPerformed

    private void FlightANDdate_status_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightANDdate_status_buttonActionPerformed
        // TODO add your handling code here:
        
        Object flight_combo_box = Flight_status_combo_box.getSelectedItem();
        Date Date_combo_box = Date.valueOf(Date_status_combo_box.getSelectedItem().toString());
        
        ArrayList <String> customers = BookingEntry.getBookingStatus(flight_combo_box.toString(), Date_combo_box);
        String status = "Customers: \n \n";
        
        for (String customer: customers) {
            status += customer + "\n";
        }
        
        FlightStatusTextArea.setText(status);
    }//GEN-LAST:event_FlightANDdate_status_buttonActionPerformed

    private void Date_status_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_status_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Date_status_combo_boxActionPerformed

    private void FlightNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FlightNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FlightNameTextFieldActionPerformed

    private void NumberOfSeatsTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NumberOfSeatsTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NumberOfSeatsTextFieldActionPerformed

    private void AddFlightNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFlightNameActionPerformed
        // TODO add your handling code here:
        String textfield = FlightNameTextField.getText();
        String textfield1 = NumberOfSeatsTextField.getText();
        new Flight().addFlightsANDSeats(textfield, textfield1);
        
        Flight_booking_combo.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        Flight_status_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        Delete_day_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        Delete_flight_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Flight.getAllFlights().toArray()));
        
        jLabel17.setText("Flight and Seat Added");
    }//GEN-LAST:event_AddFlightNameActionPerformed

    private void Date_waitlist_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Date_waitlist_buttonActionPerformed
        // TODO add your handling code here:
        
        Date waitlist_combo_box = Date.valueOf(Date_waitlist_combo_box.getSelectedItem().toString());
        int count = 1;
        
        ArrayList <String> customersANDflights = Waitlist.getWaitlist(waitlist_combo_box);
        String status = "Customers and Flights: \n \n";
        
        for (String customer_flights: customersANDflights) {
            if (count % 2 == 0) {
                status = status + "Waitlisted on Flight " + customer_flights + "\n";
                count += 1;
            }
            
            else {
                status = status + customer_flights + " - ";
                count += 1;
            }
        }
        
        Waitlist_text_area.setText(status);
    }//GEN-LAST:event_Date_waitlist_buttonActionPerformed

    private void AddDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDateActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
        String spinnerValue = formater.format(DateSpinner.getValue());
        
        new Day().addDay(spinnerValue);
        
        Dates_booking_combo.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        Date_status_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        Date_waitlist_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
        Delete_day_combo_box.setModel(new javax.swing.DefaultComboBoxModel(Day.getDays().toArray()));
                
        jLabel19.setText("Date Added");
    }//GEN-LAST:event_AddDateActionPerformed

    private void Flight_booking_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Flight_booking_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Flight_booking_comboActionPerformed

    private void customer_status_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customer_status_buttonActionPerformed
        // TODO add your handling code here:
        Object customer_combo_box = Customer_status_combo_box.getSelectedItem();
        
        ArrayList <String> flights = BookingEntry.getCustomerFlightStatus(customer_combo_box.toString());
        ArrayList <String> dates = BookingEntry.getCustomerDateStatus(customer_combo_box.toString());
        ArrayList <String> waitlist_flights = Waitlist.getWaitlistFlight(customer_combo_box.toString());
        ArrayList <String> waitlist_days = Waitlist.getWaitlistDay(customer_combo_box.toString());
        
        String status = "Flights: \n \n";
        
        for (int i = 0; i < flights.size(); i++) {
            String flight = flights.get(i);
            String date = dates.get(i);
            status = status + "Booked on " + flight + ", " + date + "\n";
            
        }
        
        for (int y = 0; y < waitlist_flights.size(); y++) {
            String waitlist_flight = waitlist_flights.get(y);
            String waitlist_day = waitlist_days.get(y);
            status = status + "Waitlisted on " + waitlist_flight + ", " + waitlist_day + "\n";
            
        }
        FlightStatusTextArea.setText(status);
    }//GEN-LAST:event_customer_status_buttonActionPerformed

    private void Drop_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Drop_buttonActionPerformed
        // TODO add your handling code here:
        Object dropped_flights = Delete_flight_combo_box.getSelectedItem();
        
        List customer_bookings = null;
        List days_bookings = null;
        List customer_waitlist = null;
        List days_waitlist = null;
        List AllFlights = null;
        
        new Flight().removeFlightsANDSeats(dropped_flights); //removes the flight from the database
        
        
        AllFlights = Flight.getAllFlights(); //arraylist
        
        customer_bookings = BookingEntry.getCustomerANDDayWithFlight(dropped_flights).get(0); //getting customer from the dropped flights
        days_bookings = BookingEntry.getCustomerANDDayWithFlight(dropped_flights).get(1); //getting days from the dropped flights
        
        customer_waitlist = Waitlist.getCustomerANDDayWithFlight(dropped_flights).get(0);
        days_waitlist = Waitlist.getCustomerANDDayWithFlight(dropped_flights).get(1);
        
        
        int i = 0;
        
        outerloop:
        for (int y = 0; y < customer_bookings.size(); y++) {
            i = 0;
            for (int z = 0; z < AllFlights.size(); z++) {
                if (BookingEntry.getFlightSeats(AllFlights.get(z).toString(), Date.valueOf(days_bookings.get(y).toString())) < Flight.getSeats((String) AllFlights.get(z))) {
                    new BookingEntry().removeBooking(customer_bookings.get(y), days_bookings.get(y));
                    new BookingEntry().addBooking(AllFlights.get(z), customer_bookings.get(y), days_bookings.get(y));
                    if (y == customer_bookings.size()-1) {
                        break outerloop;
                    }
                }
                else {
                    i += 1;
                }
            }
            if (i == AllFlights.size()) {
                new BookingEntry().removeBooking(customer_bookings.get(y), days_bookings.get(y));
            }
        }
        
        int y = 0;
        outerloop:
        for (int a = 0; a < customer_waitlist.size(); a++) {
            y = 0;
            for (int b = 0; b < AllFlights.size(); b++) {
                if (BookingEntry.getFlightSeats(AllFlights.get(b).toString(), Date.valueOf(days_waitlist.get(a).toString())) < Flight.getSeats((String) AllFlights.get(b))) {
                    new BookingEntry().removeBooking(customer_waitlist.get(a), days_waitlist.get(a));
                    new BookingEntry().addBooking(AllFlights.get(b), customer_waitlist.get(a), days_waitlist.get(a));
                    if (a == customer_waitlist.size()-1) {
                        break outerloop;
                    }
                }
                else {
                    y += 1;
                }
            }
            if (y == AllFlights.size()) {
                new Waitlist().removeWaitlist(customer_waitlist.get(a), days_waitlist.get(a));
            }
        }
        
        jLabel22.setText("Flight Dropped");
    }//GEN-LAST:event_Drop_buttonActionPerformed

    private void Customer_status_combo_boxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Customer_status_combo_boxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Customer_status_combo_boxActionPerformed

    private void cancel_booking_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_booking_buttonActionPerformed
        // TODO add your handling code here:
        Object options = Delete_customer_combo_box.getSelectedItem();
        Object options1 = Delete_day_combo_box.getSelectedItem();
        Object customer_day_flight = null;
        Object new_customer_waitlist = null;
        
        customer_day_flight = BookingEntry.getCustomerDayFlight(options, options1); //get old customer day flight
        
        new BookingEntry().removeBooking(options, options1); //delete old customer's booking
        new Waitlist().removeWaitlist(options, options1); //delete old customer from waitlist if it's present
        
        new_customer_waitlist = Waitlist.getWaitListCustomer(customer_day_flight, options1); //get new customer from waitlist
        
        if (new_customer_waitlist != "") {
            new Waitlist().removeWaitlist(new_customer_waitlist, options1); // remove new customer from waitlist
            new BookingEntry().addBooking(customer_day_flight, new_customer_waitlist, options1); //book new customer
        }
        
        String text = "Customer " + String.valueOf(options) + "\n on Flight " + customer_day_flight + " was deleted";
        jLabel23.setText(text); //remember to change this 
        
        
    }//GEN-LAST:event_cancel_booking_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBooking;
    private javax.swing.JButton AddCustomerButton;
    private javax.swing.JButton AddDate;
    private javax.swing.JButton AddFlightName;
    private javax.swing.JLabel Booking_label;
    private javax.swing.JLabel Booking_label_2;
    private javax.swing.JTextField CustomerNameTextField;
    private javax.swing.JComboBox<String> Customer_status_combo_box;
    private javax.swing.JComboBox<String> Customers_booking_combo;
    private javax.swing.JSpinner DateSpinner;
    private javax.swing.JComboBox<String> Date_status_combo_box;
    private javax.swing.JButton Date_waitlist_button;
    private javax.swing.JComboBox<String> Date_waitlist_combo_box;
    private javax.swing.JComboBox<String> Dates_booking_combo;
    private javax.swing.JComboBox<String> Delete_customer_combo_box;
    private javax.swing.JComboBox<String> Delete_day_combo_box;
    private javax.swing.JComboBox<String> Delete_flight_combo_box;
    private javax.swing.JButton Drop_button;
    private javax.swing.JButton FlightANDdate_status_button;
    private javax.swing.JTextField FlightNameTextField;
    private javax.swing.JTextArea FlightStatusTextArea;
    private javax.swing.JComboBox<String> Flight_booking_combo;
    private javax.swing.JComboBox<String> Flight_status_combo_box;
    private javax.swing.JTextField NumberOfSeatsTextField;
    private javax.swing.JTextArea Waitlist_text_area;
    private javax.swing.JButton cancel_booking_button;
    private javax.swing.JLabel customer_added_jLabel;
    private javax.swing.JButton customer_status_button;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

}
